POST http://localhost:3000/V2/ItemsTable/InsertWithChecks/ForUnique
Content-Type: application/json

{
  "ItemName": "",
  "ItemNameAlias": "",
  "ItemCode": "",
  "Rate": "",
  "GstPercentage": "",
  "hsn": ""
}