POST http://localhost:3000/SV2/ItemsTable/Insert/BulkAsIs
Content-Type: application/json

[
  {
    "ItemName": "",
    "ItemNameAlias": "",
    "ItemCode": "",
    "Rate": "",
    "GstPercentage": "",
    "hsn": ""
  }
]