POST http://localhost:3000/SV2/ItemsTable/SubTable/Insert/WithUuIdAndDT/{RowIndex}/{KeyName}
Content-Type: application/json

{
  "ItemName": "",
  "ItemNameAlias": "",
  "ItemCode": "",
  "Rate": "",
  "GstPercentage": "",
  "hsn": ""
}